version: '3.8'

services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: inventory_db
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=admin1234 --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  inventory-api:
    image: inventory-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M