app:
  trace: true
  token:
    signing:
      key: Y29sdW1uc2NyZWVuY291bnRhbGxvd3dvcmtsaWVob3JzZXdoYXR2YWx1YWJsZXByb2MY2


spring:
  application:
    name: inventory-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: admin1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate:
      format_sql: true
server:
  port: 8080
---
spring.config.activate.on-profile: docker

spring:
  datasource:
    url: jdbc:mysql://mysql/inventory_db
